<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dell-pc" name="Default test(failed)" tests="2" failures="2" timestamp="27 Jun 2017 20:41:16 GMT" time="0.006" errors="0">
  <testcase name="createUser1" time="0.001" classname="BTM.Data_provider">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [2] but found [1]
	at BTM.Data_provider.createUser1(Data_provider.java:32)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- createUser1 -->
  <testcase name="createUser1" time="0.002" classname="BTM.Data_provider">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [2] but found [1]
	at BTM.Data_provider.createUser1(Data_provider.java:32)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- createUser1 -->
</testsuite> <!-- Default test(failed) -->
